controller_list:
  - name: fake_gluon_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - axis_joint_1
      - axis_joint_2
      - axis_joint_3
      - axis_joint_4
      - axis_joint_5
      - axis_joint_6
initial:  # Define initial robot poses.
  - group: gluon_arm
    pose: Home